/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package busapplication;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tushar
 */
public class AddBusDetails extends javax.swing.JInternalFrame {
    String dbUsername="root";
    String dbrootPassword="";

    /**
     * Creates new form AddBusDetails
     */
    public AddBusDetails() {
        initComponents();
        String busnoD = busnoTF.getText();
        String bussourceD = bus_sourceTF.getText();
        String busdestD = bus_destTF.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        busnoTF = new javax.swing.JTextField();
        bus_sourceTF = new javax.swing.JTextField();
        bus_destTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dateTimeTF = new javax.swing.JTextField();
        priceTF = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        moveF = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        seatTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Add Bus Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 230, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel2.setText("Bus No");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Source");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel4.setText("Destination");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 164, -1, -1));

        busnoTF.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        busnoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busnoTFActionPerformed(evt);
            }
        });
        getContentPane().add(busnoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 117, 239, -1));

        bus_sourceTF.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        getContentPane().add(bus_sourceTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 117, 239, -1));

        bus_destTF.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        getContentPane().add(bus_destTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 164, 239, -1));

        jButton1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 352, -1, -1));

        jButton2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 352, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Movement");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 167, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel6.setText("Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 222, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Time");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 222, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel8.setText("Date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 272, -1, -1));

        dateTimeTF.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        dateTimeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTimeTFActionPerformed(evt);
            }
        });
        getContentPane().add(dateTimeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 219, 239, -1));

        priceTF.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        getContentPane().add(priceTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 219, 239, -1));

        jTextField3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 266, 239, -1));

        moveF.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        moveF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        moveF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveFActionPerformed(evt);
            }
        });
        getContentPane().add(moveF, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 164, 239, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Seat");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 269, -1, -1));

        seatTF.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        getContentPane().add(seatTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 266, 239, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tushar\\Downloads\\AddBusDetail.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void infoMessage(String message, String title) {
        JOptionPane.showMessageDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
    }

    public void cleareFieldValue() {
        busnoTF.setText("");
        bus_sourceTF.setText("");
        bus_destTF.setText("");

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String busnoD = busnoTF.getText();
        String bussourceD = bus_sourceTF.getText();
        String busdestD = bus_destTF.getText();
        String departTimeD = dateTimeTF.getText();
        String price = priceTF.getText();
        String seat = seatTF.getText();
        String busMOveD = (String) moveF.getSelectedItem();

        String jdbcUrl = "jdbc:mysql://localhost:3306/bus";
        String dbUser = dbUsername;
        String dbPassword = dbrootPassword;

        try (Connection connection = DriverManager.getConnection(jdbcUrl, dbUser, dbPassword)) {
            String selectQuery = "SELECT COUNT(*) FROM bus_details WHERE bus_no = ?";
            try (PreparedStatement preparedStatement = connection.prepareStatement(selectQuery)) {
                preparedStatement.setString(1, busnoD);

                ResultSet rs = preparedStatement.executeQuery();

                if (rs.next()) {
                    int count = rs.getInt(1); // Get the count from the first column
                    if (count > 0) {
                        infoMessage("Bus Details Are Already Added", "Created Fresh Entry!!");
                        cleareFieldValue();
                    } else {
                        String insertQuery = "INSERT INTO bus_details (bus_no, bus_source, bus_dest,depart_time,price,seat,movement) VALUES (?, ?, ?,?,?,?,?)";
                        try (PreparedStatement insertStat = connection.prepareStatement(insertQuery)) {
                            insertStat.setString(1, busnoD);
                            insertStat.setString(2, bussourceD);
                            insertStat.setString(3, busdestD);
                            insertStat.setString(4, departTimeD);
                            insertStat.setString(5, price);
                            insertStat.setString(6, seat);
                            insertStat.setString(7, busMOveD);

                            int rowsAffected = insertStat.executeUpdate();

                            if (rowsAffected > 0) {
                                System.out.println("Data inserted successfully.");
                                infoMessage("Data inserted successfully", "Successfull");
                                cleareFieldValue();

                            } else {
                                System.out.println("Failed to insert data.");
                                // Optionally, you can show an error message to the user.
                            }
                        }
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Handle any exceptions here.
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void busnoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busnoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busnoTFActionPerformed

    private void dateTimeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTimeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTimeTFActionPerformed

    private void moveFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveFActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        busnoTF.setText("");
        bus_destTF.setText("");
        bus_sourceTF.setText("");
        dateTimeTF.setText("");
        priceTF.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bus_destTF;
    private javax.swing.JTextField bus_sourceTF;
    private javax.swing.JTextField busnoTF;
    private javax.swing.JTextField dateTimeTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JComboBox<String> moveF;
    private javax.swing.JTextField priceTF;
    private javax.swing.JTextField seatTF;
    // End of variables declaration//GEN-END:variables
}
