/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package busapplication;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Tushar
 */
public class AdminRegister extends javax.swing.JInternalFrame {
    String dbUsername="root";
    String dbrootPassword="tiger";
    /**
     * Creates new form AdminRegister
     */
    public AdminRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adminnameTF = new javax.swing.JTextField();
        adminusernameTF = new javax.swing.JTextField();
        adminPF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 204, 0));
        setClosable(true);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Register");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 36, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 70, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 158, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 207, -1, -1));

        adminnameTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminnameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminnameTFActionPerformed(evt);
            }
        });
        getContentPane().add(adminnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 106, 216, -1));

        adminusernameTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(adminusernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 155, 216, -1));

        adminPF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(adminPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 204, 214, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 323, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tushar\\Downloads\\AdminRegister.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void infoMessage(String message, String title) {
        JOptionPane.showMessageDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = adminnameTF.getText();
        String username = adminusernameTF.getText();
        String password = adminPF.getText();

        if (name.trim().equals("") || username.trim().equals("") || password.trim().equals("")) {
            infoMessage("Data Incomplete!", "Empty Field");
            return;
        }

        String jdbcUrl = "jdbc:mysql://localhost:3306/bus";
        String dbUser = dbUsername;
        String dbPassword = dbrootPassword;

        try (Connection connection = DriverManager.getConnection(jdbcUrl, dbUser, dbPassword)) {
            String selectQuery = "SELECT COUNT(*) FROM Bus WHERE username = ? AND password = ?";
            try (PreparedStatement preparedStatement = connection.prepareStatement(selectQuery)) {
                preparedStatement.setString(1, username);
                preparedStatement.setString(2, password);

                ResultSet rs = preparedStatement.executeQuery();

                if (rs.next()) {
                    int count = rs.getInt(1); // Get the count from the first column
                    if (count > 0) {
                        infoMessage("Already Registered", "Successfull");
                    } else {
                        String insertQuery = "INSERT INTO admin_details (name, username, password) VALUES (?, ?, ?)";
                        try (PreparedStatement insertStat = connection.prepareStatement(insertQuery)) {
                            insertStat.setString(1, name);
                            insertStat.setString(2, username);
                            insertStat.setString(3, password);

                            int rowsAffected = insertStat.executeUpdate();

                            if (rowsAffected > 0) {
                                System.out.println("Data inserted successfully.");
                                infoMessage("Admin added!!", "Successfull");

                            } else {
                                System.out.println("Failed to insert data.");
                                // Optionally, you can show an error message to the user.
                            }
                        }
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Handle any exceptions here.
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void adminnameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminnameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminnameTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminPF;
    private javax.swing.JTextField adminnameTF;
    private javax.swing.JTextField adminusernameTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
